spring:
  application:
    name: temueats

  datasource:
    url: jdbc:postgresql://43.201.49.245/temueats
    username:
    password:

    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret:
      key: 7KCA64qU7Jik64qY7JWE66mU66as7Lm064W47JmA7LSI7L2U652865a866W866i57JeI7Iq164uI64uk7ZaJ67O17ZW07JqU

  kakao:
    api:
      key: 644ac6096d5a2d9b7df7289e65d18985