spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/temueats
    username: jason
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.cache.hibernate.cache.use_second_level_cache: true
      hibernate.cache.hibernate.cache.use_query_cache: false
      hibernate.hibernate.format_sql: true